import mongoose from "mongoose";

import Category from "../models/Category.js";
import Business from "../models/Business.js";
import BusinessType from "../models/BusinessType.js";
import User from "../models/User.js";

import {
  errorResponse,
  successResponse,
} from "../utils/apiResponse.js";

import {
  uploadToCloudinary,
  deleteFromCloudinary,
} from "../utils/cloudinaryUpload.js";

// ======================================================
// HELPERS
// ======================================================

const getUserRole = (user) =>
  user?.role?.slug ||
  user?.role?.name?.toLowerCase();

const isSuperAdmin = (user) =>
  getUserRole(user) === "super-admin";

const isValidObjectId = (id) =>
  mongoose.Types.ObjectId.isValid(id);

// ======================================================
// FORMAT CATEGORY NAME
// ======================================================
//
// Examples:
//
// "ipads"
//      -> "Ipads"
//
// "mobile phones"
//      -> "Mobile Phones"
//
// "deLL zONE"
//      -> "DeLL ZONE"
//
// "  mobile   phones  "
//      -> "Mobile Phones"
//
// We only capitalize the first character of each word.
// Existing characters remain unchanged.
//

const formatCategoryName = (value = "") => {
  return value
    .trim()
    .replace(/\s+/g, " ")
    .replace(/\b\w/g, (char) =>
      char.toUpperCase()
    );
};

// ======================================================
// GENERATE SLUG
// ======================================================
//
// Examples:
//
// "Mobiles"
//      -> "mobiles"
//
// "Mobile Phones"
//      -> "mobile-phones"
//
// "DeLL ZONE"
//      -> "dell-zone"
//
// Slug is always generated by backend.
// Frontend slug is NOT trusted.
//

const generateSlug = (value = "") => {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
};

// ======================================================
// PARSE BOOLEAN
// ======================================================

const parseBoolean = (
  value,
  defaultValue = undefined
) => {
  if (
    value === undefined ||
    value === null ||
    value === ""
  ) {
    return defaultValue;
  }

  if (
    value === true ||
    value === "true" ||
    value === 1 ||
    value === "1"
  ) {
    return true;
  }

  if (
    value === false ||
    value === "false" ||
    value === 0 ||
    value === "0"
  ) {
    return false;
  }

  return defaultValue;
};

// ======================================================
// GET EFFECTIVE BUSINESS CONTEXT
// ======================================================
//
// Super Admin:
//   Usually has no business assigned.
//
// Admin:
//   Gets business + businessType directly from user.
//
// Manager:
//   Inherits business + businessType from Admin
//   through createdBy.
//
// ======================================================

const getEffectiveBusinessContext = async (user) => {
  if (!user) {
    return null;
  }

  // ====================================================
  // ADMIN
  // ====================================================

  if (user.business) {
    return {
      business:
        user.business?._id ||
        user.business,

      businessType:
        user.businessType?._id ||
        user.businessType ||
        null,
    };
  }

  // ====================================================
  // MANAGER
  // ====================================================

  if (user.createdBy) {
    const creator =
      await User.findById(user.createdBy)
        .select("business businessType")
        .lean();

    if (!creator) {
      return null;
    }

    return {
      business:
        creator.business?._id ||
        creator.business ||
        null,

      businessType:
        creator.businessType?._id ||
        creator.businessType ||
        null,
    };
  }

  return null;
};

// ======================================================
// REQUIRE TENANT CONTEXT
// ======================================================
//
// Admin and Manager must have:
//
// Business
// +
// Business Type
//
// This prevents an Admin assigned only to a Business
// from seeing categories belonging to multiple
// Business Types.
//

const requireTenantContext = async (user) => {
  const context =
    await getEffectiveBusinessContext(user);

  if (!context?.business) {
    return {
      error:
        "Business context not found for this user",
    };
  }

  if (!context?.businessType) {
    return {
      error:
        "Business type context not found for this user",
    };
  }

  return {
    context,
  };
};

// ======================================================
// VALIDATE BUSINESS
// ======================================================

const validateBusiness = async (businessId) => {
  if (
    !businessId ||
    !isValidObjectId(businessId)
  ) {
    return null;
  }

  return Business.findOne({
    _id: businessId,
    isActive: true,
  }).lean();
};

// ======================================================
// VALIDATE BUSINESS TYPE
// ======================================================
//
// Business Type MUST belong to the selected Business.
//

const validateBusinessType = async (
  businessTypeId,
  businessId
) => {
  if (
    !businessTypeId ||
    !isValidObjectId(businessTypeId) ||
    !businessId ||
    !isValidObjectId(businessId)
  ) {
    return null;
  }

  return BusinessType.findOne({
    _id: businessTypeId,
    business: businessId,
    isActive: true,
  }).lean();
};

// ======================================================
// BUILD TENANT QUERY
// ======================================================
//
// Super Admin:
//   Optional business/businessType filters.
//
// Admin / Manager:
//   ALWAYS forced to their assigned context.
//

const buildTenantQuery = async (
  req,
  extraQuery = {}
) => {
  const query = {
    ...extraQuery,
  };

  // ====================================================
  // SUPER ADMIN
  // ====================================================

  if (isSuperAdmin(req.user)) {
    if (req.query.business) {
      if (
        !isValidObjectId(
          req.query.business
        )
      ) {
        return {
          error: "Invalid business ID",
        };
      }

      query.business =
        req.query.business;
    }

    if (req.query.businessType) {
      if (
        !isValidObjectId(
          req.query.businessType
        )
      ) {
        return {
          error:
            "Invalid business type ID",
        };
      }

      query.businessType =
        req.query.businessType;
    }

    return {
      query,
    };
  }

  // ====================================================
  // ADMIN / MANAGER
  // ====================================================

  const tenant =
    await requireTenantContext(req.user);

  if (tenant.error) {
    return {
      error: tenant.error,
    };
  }

  query.business =
    tenant.context.business;

  query.businessType =
    tenant.context.businessType;

  return {
    query,
  };
};

// ======================================================
// CREATE CATEGORY
// ======================================================

export const createCategory = async (
  req,
  res,
  next
) => {
  try {
    const {
      name,
      businessType,
      description,
      isActive,
    } = req.body;

    // ==================================================
    // BASIC VALIDATION
    // ==================================================

    if (!name?.trim()) {
      return errorResponse(
        res,
        400,
        "Category name is required"
      );
    }

    // ==================================================
    // FORMAT NAME
    // ==================================================

    const formattedName =
      formatCategoryName(name);

    if (!formattedName) {
      return errorResponse(
        res,
        400,
        "Category name is required"
      );
    }

    // ==================================================
    // GENERATE SLUG
    // ==================================================

    const generatedSlug =
      generateSlug(formattedName);

    if (!generatedSlug) {
      return errorResponse(
        res,
        400,
        "Unable to generate category slug"
      );
    }

    // ==================================================
    // GET BUSINESS CONTEXT
    // ==================================================

    let businessId = null;
    let businessTypeId = null;

    // ==================================================
    // SUPER ADMIN
    // ==================================================

    if (isSuperAdmin(req.user)) {
      businessId =
        req.body.business ||
        req.query.business ||
        null;

      businessTypeId =
        businessType || null;
    }

    // ==================================================
    // ADMIN / MANAGER
    // ==================================================

    else {
      const tenant =
        await requireTenantContext(
          req.user
        );

      if (tenant.error) {
        return errorResponse(
          res,
          400,
          tenant.error
        );
      }

      businessId =
        tenant.context.business;

      businessTypeId =
        tenant.context.businessType;
    }

    // ==================================================
    // BUSINESS REQUIRED
    // ==================================================

    if (!businessId) {
      return errorResponse(
        res,
        400,
        "Business is required"
      );
    }

    if (
      !isValidObjectId(businessId)
    ) {
      return errorResponse(
        res,
        400,
        "Invalid business ID"
      );
    }

    // ==================================================
    // VALIDATE BUSINESS
    // ==================================================

    const business =
      await validateBusiness(
        businessId
      );

    if (!business) {
      return errorResponse(
        res,
        404,
        "Business not found or inactive"
      );
    }

    // ==================================================
    // BUSINESS TYPE REQUIRED FOR ADMIN/MANAGER
    // ==================================================

    if (
      !isSuperAdmin(req.user) &&
      !businessTypeId
    ) {
      return errorResponse(
        res,
        400,
        "Business type is required for this user"
      );
    }

    // ==================================================
    // VALIDATE BUSINESS TYPE
    // ==================================================

    if (businessTypeId) {
      const validBusinessType =
        await validateBusinessType(
          businessTypeId,
          businessId
        );

      if (!validBusinessType) {
        return errorResponse(
          res,
          400,
          "Business type does not belong to this business"
        );
      }
    }

    // ==================================================
    // DUPLICATE CATEGORY CHECK
    // ==================================================

    const existingCategory =
      await Category.findOne({
        business: businessId,

        businessType:
          businessTypeId || null,

        name: formattedName,
      });

    if (existingCategory) {
      return errorResponse(
        res,
        409,
        "Category with this name already exists"
      );
    }

    // ==================================================
    // UPLOAD IMAGE
    // ==================================================

    let image = {
      url: null,
      publicId: null,
      assetId: null,
    };

    if (req.file) {
      const uploadedImage =
        await uploadToCloudinary(
          req.file.buffer,
          "pos/categories"
        );

      image = {
        url:
          uploadedImage.secure_url,

        publicId:
          uploadedImage.public_id,

        assetId:
          uploadedImage.asset_id ||
          null,
      };
    }

    // ==================================================
    // CREATE CATEGORY
    // ==================================================

    const category =
      await Category.create({
        business: businessId,

        businessType:
          businessTypeId || null,

        name: formattedName,

        slug: generatedSlug,

        image,

        description:
          description?.trim() || "",

        isActive:
          parseBoolean(
            isActive,
            true
          ),

        createdBy:
          req.user._id,
      });

    // ==================================================
    // POPULATE RESPONSE
    // ==================================================

    const populatedCategory =
      await Category.findById(
        category._id
      )
        .populate(
          "business",
          "name"
        )
        .populate(
          "businessType",
          "name"
        )
        .populate(
          "createdBy",
          "name email"
        );

    return successResponse(
      res,
      201,
      "Category created successfully",
      populatedCategory
    );
  } catch (error) {
    // MongoDB duplicate key
    if (error?.code === 11000) {
      return errorResponse(
        res,
        409,
        "Category with this name already exists"
      );
    }

    next(error);
  }
};

// ======================================================
// GET ALL CATEGORIES
// ======================================================

export const getAllCategories = async (
  req,
  res,
  next
) => {
  try {
    const {
      search,
      businessType,
      isActive,
      page = 1,
      limit = 20,
    } = req.query;

    let query = {};

    // ==================================================
    // TENANT ISOLATION
    // ==================================================

    if (isSuperAdmin(req.user)) {
      // -----------------------------------------------
      // SUPER ADMIN
      // -----------------------------------------------

      if (req.query.business) {
        if (
          !isValidObjectId(
            req.query.business
          )
        ) {
          return errorResponse(
            res,
            400,
            "Invalid business ID"
          );
        }

        query.business =
          req.query.business;
      }

      if (businessType) {
        if (
          !isValidObjectId(
            businessType
          )
        ) {
          return errorResponse(
            res,
            400,
            "Invalid business type ID"
          );
        }

        query.businessType =
          businessType;
      }
    } else {
      // -----------------------------------------------
      // ADMIN / MANAGER
      // -----------------------------------------------

      const tenant =
        await requireTenantContext(
          req.user
        );

      if (tenant.error) {
        return errorResponse(
          res,
          400,
          tenant.error
        );
      }

      query.business =
        tenant.context.business;

      query.businessType =
        tenant.context.businessType;
    }

    // ==================================================
    // SEARCH
    // ==================================================

    if (search?.trim()) {
      query.$or = [
        {
          name: {
            $regex:
              search.trim(),
            $options: "i",
          },
        },
        {
          slug: {
            $regex:
              search.trim(),
            $options: "i",
          },
        },
      ];
    }

    // ==================================================
    // ACTIVE FILTER
    // ==================================================

    if (isActive !== undefined) {
      const parsedActive =
        parseBoolean(isActive);

      if (
        parsedActive !== undefined
      ) {
        query.isActive =
          parsedActive;
      }
    }

    // ==================================================
    // PAGINATION
    // ==================================================

    const pageNumber =
      Math.max(
        Number(page) || 1,
        1
      );

    const limitNumber =
      Math.min(
        Math.max(
          Number(limit) || 20,
          1
        ),
        100
      );

    const skip =
      (pageNumber - 1) *
      limitNumber;

    // ==================================================
    // FETCH
    // ==================================================

    const [
      categories,
      total,
    ] = await Promise.all([
      Category.find(query)
        .populate(
          "business",
          "name"
        )
        .populate(
          "businessType",
          "name"
        )
        .populate(
          "createdBy",
          "name email"
        )
        .populate(
          "updatedBy",
          "name email"
        )
        .sort({
          createdAt: -1,
        })
        .skip(skip)
        .limit(limitNumber)
        .lean(),

      Category.countDocuments(
        query
      ),
    ]);

    // ==================================================
    // RESPONSE
    // ==================================================

    return successResponse(
      res,
      200,
      "Categories fetched successfully",
      {
        categories,

        pagination: {
          page: pageNumber,

          limit: limitNumber,

          total,

          totalPages:
            Math.ceil(
              total /
                limitNumber
            ),
        },
      }
    );
  } catch (error) {
    next(error);
  }
};

// ======================================================
// GET CATEGORY BY ID
// ======================================================

export const getCategoryById = async (
  req,
  res,
  next
) => {
  try {
    const { id } =
      req.params;

    // ==================================================
    // VALIDATE ID
    // ==================================================

    if (
      !isValidObjectId(id)
    ) {
      return errorResponse(
        res,
        400,
        "Invalid category ID"
      );
    }

    // ==================================================
    // BUILD TENANT QUERY
    // ==================================================

    const result =
      await buildTenantQuery(
        req,
        {
          _id: id,
        }
      );

    if (result.error) {
      return errorResponse(
        res,
        400,
        result.error
      );
    }

    // ==================================================
    // FIND CATEGORY
    // ==================================================

    const category =
      await Category.findOne(
        result.query
      )
        .populate(
          "business",
          "name"
        )
        .populate(
          "businessType",
          "name"
        )
        .populate(
          "createdBy",
          "name email"
        )
        .populate(
          "updatedBy",
          "name email"
        );

    if (!category) {
      return errorResponse(
        res,
        404,
        "Category not found"
      );
    }

    // ==================================================
    // RESPONSE
    // ==================================================

    return successResponse(
      res,
      200,
      "Category fetched successfully",
      category
    );
  } catch (error) {
    next(error);
  }
};

// ======================================================
// UPDATE CATEGORY
// ======================================================

export const updateCategory = async (
  req,
  res,
  next
) => {
  try {
    const { id } =
      req.params;

    // ==================================================
    // VALIDATE ID
    // ==================================================

    if (
      !isValidObjectId(id)
    ) {
      return errorResponse(
        res,
        400,
        "Invalid category ID"
      );
    }

    const {
      name,
      businessType,
      description,
      isActive,
      removeImage,
    } = req.body;

    // ==================================================
    // FIND CATEGORY WITH TENANT ISOLATION
    // ==================================================

    const result =
      await buildTenantQuery(
        req,
        {
          _id: id,
        }
      );

    if (result.error) {
      return errorResponse(
        res,
        400,
        result.error
      );
    }

    const category =
      await Category.findOne(
        result.query
      );

    if (!category) {
      return errorResponse(
        res,
        404,
        "Category not found"
      );
    }

    const businessId =
      category.business?.toString();

    // ==================================================
    // BUSINESS TYPE
    // ==================================================

    let newBusinessType =
      category.businessType
        ? category.businessType.toString()
        : null;

    // ==================================================
    // SUPER ADMIN
    // ==================================================

    if (isSuperAdmin(req.user)) {
      if (
        businessType !==
        undefined
      ) {
        // Allow Super Admin to remove
        // Business Type.

        if (
          businessType === null ||
          businessType === ""
        ) {
          newBusinessType =
            null;
        } else {
          if (
            !isValidObjectId(
              businessType
            )
          ) {
            return errorResponse(
              res,
              400,
              "Invalid business type ID"
            );
          }

          const validBusinessType =
            await validateBusinessType(
              businessType,
              businessId
            );

          if (
            !validBusinessType
          ) {
            return errorResponse(
              res,
              400,
              "Business type does not belong to this business"
            );
          }

          newBusinessType =
            businessType.toString();
        }
      }
    }

    // ==================================================
    // ADMIN / MANAGER
    // ==================================================

    else {
      const tenant =
        await requireTenantContext(
          req.user
        );

      if (tenant.error) {
        return errorResponse(
          res,
          400,
          tenant.error
        );
      }

      // NEVER trust businessType
      // from request.

      newBusinessType =
        tenant.context.businessType.toString();
    }

    // ==================================================
    // UPDATE NAME
    // ==================================================

    if (
      name !== undefined
    ) {
      if (
        !name?.trim()
      ) {
        return errorResponse(
          res,
          400,
          "Category name cannot be empty"
        );
      }

      category.name =
        formatCategoryName(
          name
        );

      // ================================================
      // ALWAYS REGENERATE SLUG
      // ================================================

      category.slug =
        generateSlug(
          category.name
        );
    }

    // ==================================================
    // UPDATE BUSINESS TYPE
    // ==================================================

    category.businessType =
      newBusinessType || null;

    // ==================================================
    // UPDATE DESCRIPTION
    // ==================================================

    if (
      description !==
      undefined
    ) {
      category.description =
        description?.trim() ||
        "";
    }

    // ==================================================
    // UPDATE ACTIVE STATUS
    // ==================================================

    if (
      isActive !== undefined
    ) {
      category.isActive =
        parseBoolean(
          isActive,
          category.isActive
        );
    }

    // ==================================================
    // REMOVE IMAGE
    // ==================================================

    if (
      parseBoolean(
        removeImage,
        false
      ) &&
      category.image?.publicId
    ) {
      await deleteFromCloudinary(
        category.image.publicId
      );

      category.image = {
        url: null,
        publicId: null,
        assetId: null,
      };
    }

    // ==================================================
    // UPLOAD NEW IMAGE
    // ==================================================

    if (req.file) {
      // Delete old image first

      if (
        category.image?.publicId
      ) {
        await deleteFromCloudinary(
          category.image.publicId
        );
      }

      const uploadedImage =
        await uploadToCloudinary(
          req.file.buffer,
          "pos/categories"
        );

      category.image = {
        url:
          uploadedImage.secure_url,

        publicId:
          uploadedImage.public_id,

        assetId:
          uploadedImage.asset_id ||
          null,
      };
    }

    // ==================================================
    // DUPLICATE CATEGORY CHECK
    // ==================================================

    const duplicate =
      await Category.findOne({
        _id: {
          $ne:
            category._id,
        },

        business:
          businessId,

        businessType:
          newBusinessType ||
          null,

        name:
          category.name,
      });

    if (duplicate) {
      return errorResponse(
        res,
        409,
        "Category with this name already exists"
      );
    }

    // ==================================================
    // UPDATE AUDIT
    // ==================================================

    category.updatedBy =
      req.user._id;

    // ==================================================
    // SAVE
    // ==================================================

    await category.save();

    // ==================================================
    // POPULATE RESPONSE
    // ==================================================

    const updatedCategory =
      await Category.findById(
        category._id
      )
        .populate(
          "business",
          "name"
        )
        .populate(
          "businessType",
          "name"
        )
        .populate(
          "createdBy",
          "name email"
        )
        .populate(
          "updatedBy",
          "name email"
        );

    // ==================================================
    // RESPONSE
    // ==================================================

    return successResponse(
      res,
      200,
      "Category updated successfully",
      updatedCategory
    );
  } catch (error) {
    // MongoDB duplicate key

    if (
      error?.code ===
      11000
    ) {
      return errorResponse(
        res,
        409,
        "Category with this name already exists"
      );
    }

    next(error);
  }
};

// ======================================================
// DELETE CATEGORY
// ======================================================
//
// Soft delete.
// Image is NOT deleted because category can be restored.
//

export const deleteCategory = async (
  req,
  res,
  next
) => {
  try {
    const { id } =
      req.params;

    // ==================================================
    // VALIDATE ID
    // ==================================================

    if (
      !isValidObjectId(id)
    ) {
      return errorResponse(
        res,
        400,
        "Invalid category ID"
      );
    }

    // ==================================================
    // TENANT QUERY
    // ==================================================

    const result =
      await buildTenantQuery(
        req,
        {
          _id: id,
        }
      );

    if (result.error) {
      return errorResponse(
        res,
        400,
        result.error
      );
    }

    // ==================================================
    // FIND CATEGORY
    // ==================================================

    const category =
      await Category.findOne(
        result.query
      );

    if (!category) {
      return errorResponse(
        res,
        404,
        "Category not found"
      );
    }

    // ==================================================
    // ALREADY DELETED
    // ==================================================

    if (
      !category.isActive
    ) {
      return errorResponse(
        res,
        400,
        "Category is already inactive"
      );
    }

    // ==================================================
    // SOFT DELETE
    // ==================================================

    category.isActive =
      false;

    category.updatedBy =
      req.user._id;

    await category.save();

    // ==================================================
    // RESPONSE
    // ==================================================

    return successResponse(
      res,
      200,
      "Category deleted successfully"
    );
  } catch (error) {
    next(error);
  }
};

// ======================================================
// RESTORE CATEGORY
// ======================================================

export const restoreCategory = async (
  req,
  res,
  next
) => {
  try {
    const { id } =
      req.params;

    // ==================================================
    // VALIDATE ID
    // ==================================================

    if (
      !isValidObjectId(id)
    ) {
      return errorResponse(
        res,
        400,
        "Invalid category ID"
      );
    }

    // ==================================================
    // TENANT QUERY
    // ==================================================

    const result =
      await buildTenantQuery(
        req,
        {
          _id: id,
        }
      );

    if (result.error) {
      return errorResponse(
        res,
        400,
        result.error
      );
    }

    // ==================================================
    // FIND CATEGORY
    // ==================================================

    const category =
      await Category.findOne(
        result.query
      );

    if (!category) {
      return errorResponse(
        res,
        404,
        "Category not found"
      );
    }

    // ==================================================
    // ALREADY ACTIVE
    // ==================================================

    if (
      category.isActive
    ) {
      return errorResponse(
        res,
        400,
        "Category is already active"
      );
    }

    // ==================================================
    // CHECK DUPLICATE ACTIVE CATEGORY
    // ==================================================
    //
    // Important because this category may have been
    // soft-deleted while another active category with
    // the same business/businessType/name exists.
    //

    const duplicate =
      await Category.findOne({
        _id: {
          $ne:
            category._id,
        },

        business:
          category.business,

        businessType:
          category.businessType,

        name:
          category.name,

        isActive: true,
      });

    if (duplicate) {
      return errorResponse(
        res,
        409,
        "An active category with this name already exists"
      );
    }

    // ==================================================
    // RESTORE
    // ==================================================

    category.isActive =
      true;

    category.updatedBy =
      req.user._id;

    await category.save();

    // ==================================================
    // POPULATE
    // ==================================================

    const restoredCategory =
      await Category.findById(
        category._id
      )
        .populate(
          "business",
          "name"
        )
        .populate(
          "businessType",
          "name"
        )
        .populate(
          "createdBy",
          "name email"
        )
        .populate(
          "updatedBy",
          "name email"
        );

    // ==================================================
    // RESPONSE
    // ==================================================

    return successResponse(
      res,
      200,
      "Category restored successfully",
      restoredCategory
    );
  } catch (error) {
    // MongoDB duplicate key

    if (
      error?.code ===
      11000
    ) {
      return errorResponse(
        res,
        409,
        "Category with this name already exists"
      );
    }

    next(error);
  }
};